# Generated by Django 6.0.2 on 2026-03-06 20:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('registration_start', models.DateTimeField()),
                ('registration_end', models.DateTimeField()),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('max_teams', models.PositiveIntegerField(blank=True, null=True)),
                ('number_of_rounds', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Registration', 'Registration'), ('Running', 'Running'), ('Finished', 'Finished')], default='Draft', max_length=20)),
            ],
        ),
    ]
